import type {
  DashboardMetrics,
  Booking,
  Task,
  Review,
  Property,
  Guest,
  BrainEntry,
  RoadmapModule,
} from './types';

export const farmsteadProperties: Property[] = [
  {
    id: 'b1b2c3d4-0001-0001-0001-000000000001',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    name: "Woody's Cottage",
    type: 'cottage',
    property_type: 'Self-catering cottage',
    status: 'active',
    google_maps_url: 'https://maps.app.goo.gl/fcWPWnpqP4tP3MfS9',
    google_review_url: 'https://example.com/google-review-woodys',
    created_at: new Date().toISOString(),
  },
  {
    id: 'b1b2c3d4-0001-0001-0001-000000000002',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    name: 'Swallows Nest Studio',
    type: 'studio',
    property_type: 'Self-catering studio',
    status: 'active',
    google_maps_url: 'https://maps.app.goo.gl/AMQ7izhTSbrkVqRg7',
    google_review_url: 'https://example.com/google-review-swallows',
    airbnb_url: 'https://example.com/airbnb-swallows',
    booking_url: 'https://example.com/booking-swallows',
    lekkeslaap_url: 'https://example.com/lekkeslaap-swallows',
    created_at: new Date().toISOString(),
  },
  {
    id: 'b1b2c3d4-0001-0001-0001-000000000003',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    name: 'Meadows Cottage',
    type: 'cottage',
    property_type: 'Self-catering cottage',
    status: 'active',
    google_maps_url: 'https://maps.app.goo.gl/fcWPWnpqP4tP3MfS9',
    google_review_url: 'https://example.com/google-review-meadows',
    created_at: new Date().toISOString(),
  },
  {
    id: 'b1b2c3d4-0001-0001-0001-000000000004',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    name: 'Jackals Rest',
    type: 'lodge',
    property_type: 'Cottage / lodge-style stay',
    status: 'active',
    google_maps_url: 'https://maps.app.goo.gl/k1Y3mPrm7cDkLwKL6',
    google_review_url: 'https://example.com/google-review-jackals',
    airbnb_url: 'https://www.airbnb.ae/rooms/53438771',
    booking_url: 'https://example.com/booking-jackals',
    lekkeslaap_url: 'https://example.com/lekkeslaap-jackals',
    operational_email: 'jackalsrest@gmail.com',
    created_at: new Date().toISOString(),
  },
];

export const mockMetrics: DashboardMetrics = {
  occupancy_rate: 73,
  occupancy_trend: 8,
  adr: 1850,
  revpar: 1350,
  open_tasks: 7,
  overdue_tasks: 2,
  pending_reviews: 3,
  avg_rating: 4.8,
  arrivals_today: 1,
  departures_today: 2,
  revenue_this_month: 42800,
  revenue_trend: 12,
};

const today = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const addDays = (d: Date, n: number) => {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r;
};

export const mockBookings: Booking[] = [
  {
    id: 'bk-001',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000004',
    source: 'airbnb',
    status: 'checked_in',
    check_in: fmt(addDays(today, -1)),
    check_out: fmt(addDays(today, 3)),
    guest_name: 'Sarah & Mark Thompson',
    adults: 2,
    total_amount: 7400,
    currency: 'ZAR',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bk-002',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000001',
    source: 'booking_com',
    status: 'confirmed',
    check_in: fmt(addDays(today, 2)),
    check_out: fmt(addDays(today, 5)),
    guest_name: 'James Nkosi',
    adults: 1,
    total_amount: 4200,
    currency: 'ZAR',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bk-003',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000002',
    source: 'direct',
    status: 'confirmed',
    check_in: fmt(today),
    check_out: fmt(addDays(today, 4)),
    guest_name: 'Priya Govender',
    adults: 2,
    children: 1,
    total_amount: 5600,
    currency: 'ZAR',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bk-004',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000003',
    source: 'lekkeslaap',
    status: 'confirmed',
    check_in: fmt(addDays(today, 7)),
    check_out: fmt(addDays(today, 10)),
    guest_name: 'Kobus & Anel van der Berg',
    adults: 2,
    total_amount: 6300,
    currency: 'ZAR',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bk-005',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000001',
    source: 'airbnb',
    status: 'checked_out',
    check_in: fmt(addDays(today, -5)),
    check_out: fmt(addDays(today, -1)),
    guest_name: 'Lindiwe Dlamini',
    adults: 2,
    total_amount: 5200,
    currency: 'ZAR',
    created_at: addDays(today, -10).toISOString(),
  },
];

// ─── Mock reservation data ────────────────────────────────────────────────────

const PROP1 = 'b1b2c3d4-0001-0001-0001-000000000001'; // Woody's Cottage
const PROP2 = 'b1b2c3d4-0001-0001-0001-000000000002'; // Swallows Nest
const PROP3 = 'b1b2c3d4-0001-0001-0001-000000000003'; // Meadows Cottage
const PROP4 = 'b1b2c3d4-0001-0001-0001-000000000004'; // Jackals Rest

export const mockRoomTypes = [
  { id: 'rt-001', property_id: PROP1, name: "Woody's Cottage", code: 'WDY', max_occupancy: 6, bed_configuration: '1 king + 2 singles', is_active: true },
  { id: 'rt-002', property_id: PROP2, name: 'Swallows Nest Studio', code: 'SWN', max_occupancy: 2, bed_configuration: '1 queen', is_active: true },
  { id: 'rt-003', property_id: PROP3, name: 'Meadows Cottage', code: 'MDW', max_occupancy: 4, bed_configuration: '1 king + 1 double', is_active: true },
  { id: 'rt-004', property_id: PROP4, name: 'Jackals Rest', code: 'JKL', max_occupancy: 8, bed_configuration: '2 king + 2 singles', is_active: true },
];

export const mockRatePlans = [
  { id: 'rp-001', property_id: PROP1, name: 'Standard Rate', code: 'STD', meal_plan: 'self_catering', min_nights: 2, is_active: true },
  { id: 'rp-002', property_id: PROP2, name: 'Standard Rate', code: 'STD', meal_plan: 'self_catering', min_nights: 1, is_active: true },
  { id: 'rp-003', property_id: PROP3, name: 'Standard Rate', code: 'STD', meal_plan: 'self_catering', min_nights: 2, is_active: true },
  { id: 'rp-004', property_id: PROP4, name: 'Standard Rate', code: 'STD', meal_plan: 'self_catering', min_nights: 2, is_active: true },
  { id: 'rp-005', property_id: PROP4, name: 'Weekend Rate', code: 'WKD', meal_plan: 'self_catering', min_nights: 2, is_active: true },
];

export const mockReservations = [
  {
    id: 'res-001', property_id: PROP4, room_type_id: 'rt-004', rate_plan_id: 'rp-004',
    confirmation_number: 'PULSE-A3F8D1', channel_code: 'airbnb',
    check_in_date: fmt(addDays(today, -1)), check_out_date: fmt(addDays(today, 3)),
    booked_at: addDays(today, -14).toISOString(),
    adults: 2, children: 0, status: 'checked_in', source: 'airbnb',
    total_amount: 7400, outstanding_balance: 0, currency: 'ZAR',
    guest_name: 'Sarah & Mark Thompson', guest_email: 'sarah.thompson@gmail.com', guest_phone: '+27 82 111 2233',
    property_name: 'Jackals Rest', room_type_name: 'Jackals Rest',
  },
  {
    id: 'res-002', property_id: PROP1, room_type_id: 'rt-001', rate_plan_id: 'rp-001',
    confirmation_number: 'PULSE-B7C2E4', channel_code: 'booking_com',
    check_in_date: fmt(addDays(today, 2)), check_out_date: fmt(addDays(today, 5)),
    booked_at: addDays(today, -7).toISOString(),
    adults: 1, children: 0, status: 'confirmed', source: 'booking_com',
    total_amount: 4200, outstanding_balance: 4200, currency: 'ZAR',
    guest_name: 'James Nkosi', guest_email: 'james.nkosi@outlook.com', guest_phone: '+27 71 444 5566',
    property_name: "Woody's Cottage", room_type_name: "Woody's Cottage",
  },
  {
    id: 'res-003', property_id: PROP2, room_type_id: 'rt-002', rate_plan_id: 'rp-002',
    confirmation_number: 'PULSE-C9D1F6', channel_code: 'direct',
    check_in_date: fmt(today), check_out_date: fmt(addDays(today, 4)),
    booked_at: addDays(today, -3).toISOString(),
    adults: 2, children: 1, status: 'confirmed', source: 'direct',
    total_amount: 5600, outstanding_balance: 2800, currency: 'ZAR',
    guest_name: 'Priya Govender', guest_email: 'priya.govender@gmail.com', guest_phone: '+27 83 777 8899',
    property_name: 'Swallows Nest Studio', room_type_name: 'Swallows Nest Studio',
  },
  {
    id: 'res-004', property_id: PROP3, room_type_id: 'rt-003', rate_plan_id: 'rp-003',
    confirmation_number: 'PULSE-D4E8A2', channel_code: 'lekke_slaap',
    check_in_date: fmt(addDays(today, 7)), check_out_date: fmt(addDays(today, 10)),
    booked_at: addDays(today, -5).toISOString(),
    adults: 2, children: 0, status: 'confirmed', source: 'lekke_slaap',
    total_amount: 6300, outstanding_balance: 6300, currency: 'ZAR',
    guest_name: 'Kobus & Anel van der Berg', guest_email: 'kobus.vdberg@icloud.com', guest_phone: '+27 79 333 4455',
    property_name: 'Meadows Cottage', room_type_name: 'Meadows Cottage',
  },
  {
    id: 'res-005', property_id: PROP1, room_type_id: 'rt-001', rate_plan_id: 'rp-001',
    confirmation_number: 'PULSE-E2F9B3', channel_code: 'airbnb',
    check_in_date: fmt(addDays(today, -5)), check_out_date: fmt(addDays(today, -1)),
    booked_at: addDays(today, -20).toISOString(),
    adults: 2, children: 0, status: 'checked_out', source: 'airbnb',
    total_amount: 5200, outstanding_balance: 0, currency: 'ZAR',
    guest_name: 'Lindiwe Dlamini', guest_email: 'lindiwe.dlamini@gmail.com', guest_phone: '+27 66 555 6677',
    property_name: "Woody's Cottage", room_type_name: "Woody's Cottage",
  },
  {
    id: 'res-006', property_id: PROP4, room_type_id: 'rt-004', rate_plan_id: 'rp-005',
    confirmation_number: 'PULSE-F5G3H1', channel_code: 'direct',
    check_in_date: fmt(addDays(today, 14)), check_out_date: fmt(addDays(today, 17)),
    booked_at: today.toISOString(),
    adults: 4, children: 2, status: 'deposit_paid', source: 'direct',
    total_amount: 9800, outstanding_balance: 4900, currency: 'ZAR',
    guest_name: 'De Wet Family', guest_email: 'dewet.family@gmail.com', guest_phone: '+27 82 999 0011',
    property_name: 'Jackals Rest', room_type_name: 'Jackals Rest',
    special_requests: 'Cot for baby, extra towels',
  },
  {
    id: 'res-007', property_id: PROP3, room_type_id: 'rt-003', rate_plan_id: 'rp-003',
    confirmation_number: 'PULSE-G8H4I2', channel_code: 'booking_com',
    check_in_date: fmt(addDays(today, 21)), check_out_date: fmt(addDays(today, 25)),
    booked_at: addDays(today, -2).toISOString(),
    adults: 2, children: 0, status: 'confirmed', source: 'booking_com',
    total_amount: 8400, outstanding_balance: 8400, currency: 'ZAR',
    guest_name: 'Rudi & Helena Joubert', guest_email: 'rudi.joubert@telkom.net', guest_phone: '+27 84 222 3344',
    property_name: 'Meadows Cottage', room_type_name: 'Meadows Cottage',
  },
  {
    id: 'res-008', property_id: PROP2, room_type_id: 'rt-002', rate_plan_id: 'rp-002',
    confirmation_number: 'PULSE-H1I7J5', channel_code: 'direct',
    check_in_date: fmt(today), check_out_date: fmt(addDays(today, 2)),
    booked_at: addDays(today, -1).toISOString(),
    adults: 1, children: 0, status: 'checked_in', source: 'direct',
    total_amount: 2200, outstanding_balance: 0, currency: 'ZAR',
    guest_name: 'Thabo Mokoena', guest_email: 'thabo.m@gmail.com', guest_phone: '+27 73 888 9900',
    property_name: 'Swallows Nest Studio', room_type_name: 'Swallows Nest Studio',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'tk-001',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000002',
    title: 'Pre-arrival clean — Swallows Nest Studio',
    category: 'housekeeping',
    status: 'open',
    priority: 'high',
    due_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'tk-002',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000004',
    title: 'Replace broken cabinet hinge — main bedroom',
    category: 'maintenance',
    status: 'in_progress',
    priority: 'medium',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tk-003',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000001',
    title: "Post-checkout inspection — Woody's Cottage",
    category: 'inspection',
    status: 'overdue',
    priority: 'high',
    due_at: addDays(today, -1).toISOString(),
    created_at: addDays(today, -2).toISOString(),
  },
  {
    id: 'tk-004',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000004',
    title: 'Prepare welcome pack — Jackals Rest arrival',
    category: 'guest_services',
    status: 'open',
    priority: 'medium',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tk-005',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000003',
    title: 'Weekly linen restock — Meadows Cottage',
    category: 'housekeeping',
    status: 'open',
    priority: 'low',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tk-006',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000002',
    title: 'Investigate hot water complaint — Swallows Nest',
    category: 'maintenance',
    status: 'overdue',
    priority: 'urgent',
    due_at: addDays(today, -1).toISOString(),
    created_at: addDays(today, -2).toISOString(),
  },
  {
    id: 'tk-007',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000004',
    title: 'Respond to Airbnb 5-star review',
    category: 'guest_services',
    status: 'open',
    priority: 'low',
    created_at: new Date().toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rv-001',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000004',
    platform: 'airbnb',
    source: 'airbnb',
    rating: 5,
    title: 'Absolutely magical farm stay',
    content: 'The most peaceful place we have stayed. The fireplace was perfect on cold nights and the host was incredibly responsive.',
    review_text: 'The most peaceful place we have stayed. The fireplace was perfect on cold nights and the host was incredibly responsive.',
    sentiment: 'positive',
    response_status: 'pending',
    topics: ['atmosphere', 'host', 'fireplace'],
    review_date: addDays(today, -3).toISOString(),
    created_at: addDays(today, -3).toISOString(),
  },
  {
    id: 'rv-002',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000001',
    platform: 'google',
    source: 'google',
    rating: 4,
    content: 'Beautiful setting, cottage was clean and well-equipped. WiFi could be stronger in the bedroom.',
    review_text: 'Beautiful setting, cottage was clean and well-equipped. WiFi could be stronger in the bedroom.',
    sentiment: 'positive',
    response_status: 'draft_ready',
    ai_response_draft:
      "Thank you for staying with us at Woody's Cottage! We're so glad you enjoyed the setting and found everything well-equipped. We hear you on the WiFi — we're planning a signal booster installation for the bedroom area next month. Hope to welcome you back!",
    recommended_response:
      "Thank you for staying with us at Woody's Cottage! We're so glad you enjoyed the setting and found everything well-equipped. We hear you on the WiFi — we're planning a signal booster installation for the bedroom area next month. Hope to welcome you back!",
    topics: ['cleanliness', 'wifi', 'location'],
    review_date: addDays(today, -7).toISOString(),
    created_at: addDays(today, -7).toISOString(),
  },
  {
    id: 'rv-003',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000002',
    platform: 'booking_com',
    source: 'booking_com',
    rating: 3,
    title: 'Good but hot water issue',
    content: 'Nice property but we had hot water problems on day 2. Took a few hours to sort out.',
    review_text: 'Nice property but we had hot water problems on day 2. Took a few hours to sort out.',
    sentiment: 'negative',
    response_status: 'pending',
    topics: ['hot water', 'maintenance', 'response time'],
    review_date: addDays(today, -2).toISOString(),
    created_at: addDays(today, -2).toISOString(),
  },
];

export const mockGuests: Guest[] = [
  {
    id: 'g-001',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    first_name: 'Sarah',
    last_name: 'Thompson',
    name: 'Sarah Thompson',
    email: 'sarah.thompson@email.com',
    phone: '+27821234567',
    country: 'South Africa',
    total_stays: 3,
    last_stay_at: fmt(addDays(today, -1)),
    created_at: addDays(today, -180).toISOString(),
  },
  {
    id: 'g-002',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    first_name: 'James',
    last_name: 'Nkosi',
    name: 'James Nkosi',
    email: 'james.nkosi@email.com',
    phone: '+27831234567',
    country: 'South Africa',
    total_stays: 1,
    created_at: addDays(today, -30).toISOString(),
  },
  {
    id: 'g-003',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    first_name: 'Priya',
    last_name: 'Govender',
    name: 'Priya Govender',
    email: 'priya.govender@email.com',
    phone: '+27841234567',
    country: 'South Africa',
    total_stays: 2,
    last_stay_at: fmt(addDays(today, -60)),
    created_at: addDays(today, -200).toISOString(),
  },
  {
    id: 'g-004',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    first_name: 'Kobus',
    last_name: 'van der Berg',
    name: 'Kobus van der Berg',
    email: 'kobus.vdberg@email.com',
    phone: '+27851234567',
    country: 'South Africa',
    total_stays: 1,
    created_at: addDays(today, -14).toISOString(),
  },
  {
    id: 'g-005',
    organization_id: 'a1b2c3d4-0001-0001-0001-000000000001',
    first_name: 'Lindiwe',
    last_name: 'Dlamini',
    name: 'Lindiwe Dlamini',
    email: 'lindiwe.dlamini@email.com',
    phone: '+27861234567',
    country: 'South Africa',
    total_stays: 4,
    last_stay_at: fmt(addDays(today, -1)),
    notes: "Repeat guest. Prefers Woody's Cottage. Allergic to feather pillows.",
    created_at: addDays(today, -365).toISOString(),
  },
];

export const brainEntries: BrainEntry[] = [
  {
    id: 'brain-001',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000004',
    category: 'wifi',
    title: 'Jackals Rest WiFi',
    content:
      'Network: JoyWood Farm Guest. Keep router powered during loadshedding checks. Escalate repeated dropouts to maintenance before guest arrival.',
    guest_visible: true,
  },
  {
    id: 'brain-002',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000004',
    category: 'sop',
    title: 'Jackals Rest fireplace procedure',
    content:
      'Open flue fully before lighting. Use dry wood only. If smoke enters the room, open the flue and nearest window, then log a maintenance note.',
    guest_visible: true,
  },
  {
    id: 'brain-003',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000002',
    category: 'maintenance',
    title: 'Swallows Nest hot water watch item',
    content:
      'Recent guest feedback mentioned hot water delay. Inspect geyser timer and pressure before next arrival. If repeated, convert to works item.',
    guest_visible: false,
  },
  {
    id: 'brain-004',
    property_id: 'b1b2c3d4-0001-0001-0001-000000000001',
    category: 'lesson',
    title: "Woody's Cottage WiFi improvement",
    content:
      'Bedroom WiFi signal is a known improvement opportunity. Add repeater before peak holiday season and mention upgrade in review response draft.',
    guest_visible: false,
  },
  {
    id: 'brain-005',
    category: 'guest_guide',
    title: 'Local recommendations baseline',
    content:
      'Maintain a curated local guide covering restaurants, cafes, farm stalls, walking routes, family activities, emergency contacts and rainy-day options.',
    guest_visible: true,
  },
];

export const aiRecommendations = [
  {
    id: 'ai-001',
    type: 'review_response',
    title: 'Draft response for Swallows Nest hot water review',
    property: 'Swallows Nest Studio',
    risk: 'medium',
    confidence: 82,
    action: 'Draft only. Human approval required before publishing.',
  },
  {
    id: 'ai-002',
    type: 'booking_gap',
    title: 'Meadows Cottage has a 3-night gap next week',
    property: 'Meadows Cottage',
    risk: 'low',
    confidence: 74,
    action: 'Suggest a last-minute LekkeSlaap promotion or direct-return guest offer.',
  },
  {
    id: 'ai-003',
    type: 'guest_message',
    title: 'Jackals Rest post-checkout review request window',
    property: 'Jackals Rest',
    risk: 'low',
    confidence: 91,
    action: 'Prepare WhatsApp draft. Do not send automatically.',
  },
];

export const roadmapModules: RoadmapModule[] = [
  {
    phase: 2,
    slug: 'visibility',
    title: 'Hospitality Visibility Intelligence',
    status: 'locked',
    audience: 'Hospitality operators and marketing teams',
    promise:
      'Google profile health, review intelligence, sentiment, social visibility and public reputation readiness.',
  },
  {
    phase: 3,
    slug: 'growth',
    title: 'Hospitality Growth Intelligence',
    status: 'locked',
    audience: 'Hospitality groups and revenue owners',
    promise:
      'Revenue intelligence, occupancy forecasting, demand signals, packages, repeat guests and direct booking uplift.',
  },
  {
    phase: 4,
    slug: 'local-ecosystem',
    title: 'Local Ecosystem Intelligence',
    status: 'locked',
    audience: 'Local businesses and destination partners',
    promise:
      'Verified profiles for restaurants, cafes, tour operators, attractions and activity providers.',
  },
  {
    phase: 5,
    slug: 'destination',
    title: 'Destination Intelligence',
    status: 'locked',
    audience: 'Tourism boards and destination managers',
    promise:
      'District dashboards, tourism activation, visitor movement, local participation and campaign performance.',
  },
  {
    phase: 6,
    slug: 'opportunities',
    title: 'Opportunity Participation Intelligence',
    status: 'locked',
    audience: 'Public-private programme teams',
    promise:
      'Opportunity builder, business verification, viability analysis, participation recommendations and outcome tracking.',
  },
  {
    phase: 7,
    slug: 'economic-intelligence',
    title: 'Economic / Government Intelligence',
    status: 'locked',
    audience: 'Government, funders and economic development stakeholders',
    promise:
      'SME participation, sector intelligence, tourism recovery reporting and measurable impact dashboards.',
  },
];
