create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

create type user_role as enum ('super_admin','platform_admin','org_owner','group_manager','property_manager','front_desk','housekeeping_supervisor','housekeeper','maintenance_manager','maintenance_vendor','finance_user','marketing_user','concierge_user','executive_readonly','destination_analyst');
create type task_status as enum ('open','in_progress','blocked','completed','cancelled','overdue');
create type risk_level as enum ('low','medium','high','critical');
create type approval_status as enum ('draft','pending_approval','approved','rejected','executed','cancelled');
create type booking_status as enum ('pending','confirmed','checked_in','checked_out','cancelled','no_show');

create table organizations (id uuid primary key default gen_random_uuid(), name text not null, legal_name text, country text default 'South Africa', default_currency text default 'ZAR', subscription_plan text default 'starter', billing_status text default 'trial', created_at timestamptz default now(), updated_at timestamptz default now());
create table organization_members (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, user_id uuid references auth.users(id) on delete cascade not null, role user_role not null default 'org_owner', permissions text[] default '{}', created_at timestamptz default now(), unique(organization_id,user_id));
create table properties (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, name text not null, property_type text not null, address text, city text, province text, country text default 'South Africa', latitude numeric, longitude numeric, google_place_id text, timezone text default 'Africa/Johannesburg', room_count int default 0, website_url text, phone text, email text, description text, amenities jsonb default '[]', brand_assets jsonb default '{}', status text default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table property_users (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id) on delete cascade not null, user_id uuid references auth.users(id) on delete cascade not null, role user_role not null, created_at timestamptz default now(), unique(property_id,user_id));
create table units (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id) on delete cascade not null, unit_name text not null, unit_type text, max_occupancy int default 2, base_rate numeric default 0, amenities jsonb default '[]', status text default 'active', created_at timestamptz default now());
create table guests (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, first_name text, last_name text, email text, phone text, country text, language_preference text default 'en', marketing_consent boolean default false, whatsapp_consent boolean default false, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table bookings (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id) on delete cascade not null, guest_id uuid references guests(id), source text not null default 'manual', external_booking_id text, check_in_date date not null, check_out_date date not null, booking_date date default current_date, unit_id uuid references units(id), status booking_status default 'confirmed', total_amount numeric default 0, currency text default 'ZAR', adults int default 1, children int default 0, special_requests text, payment_status text default 'unknown', channel_commission numeric default 0, created_at timestamptz default now(), updated_at timestamptz default now(), constraint valid_booking_dates check (check_out_date > check_in_date));
create table event_log (id uuid primary key default gen_random_uuid(), event_type text not null, organization_id uuid references organizations(id) on delete cascade, property_id uuid references properties(id) on delete cascade, actor_type text default 'system', actor_id uuid, source_system text default 'pulse', payload jsonb default '{}', correlation_id uuid default gen_random_uuid(), idempotency_key text, created_at timestamptz default now());
create table tasks (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, property_id uuid references properties(id) on delete cascade not null, title text not null, description text, category text not null default 'operations', priority risk_level default 'medium', status task_status default 'open', assigned_to uuid references auth.users(id), source_event_id uuid references event_log(id), ai_generated boolean default false, requires_approval boolean default false, approved_by uuid references auth.users(id), due_at timestamptz, completed_at timestamptz, evidence_required boolean default false, evidence_files jsonb default '[]', recurrence_rule text, created_at timestamptz default now(), updated_at timestamptz default now());
create table workflows (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, property_id uuid references properties(id) on delete cascade, name text not null, trigger_event_type text not null, conditions jsonb default '{}', actions jsonb not null default '[]', enabled boolean default true, version int default 1, created_by uuid references auth.users(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table notifications (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, property_id uuid references properties(id) on delete cascade, user_id uuid references auth.users(id), channel text not null default 'app', title text not null, message text, priority risk_level default 'medium', status text default 'queued', related_entity_type text, related_entity_id uuid, sent_at timestamptz, read_at timestamptz, created_at timestamptz default now());
create table reviews (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id) on delete cascade not null, source text not null, external_review_id text, guest_name text, rating numeric, review_text text, sentiment_score numeric, topics text[] default '{}', ai_summary text, response_status approval_status default 'draft', recommended_response text, published_response text, created_at timestamptz default now(), updated_at timestamptz default now());
create table social_campaigns (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id) on delete cascade not null, campaign_name text not null, campaign_type text, objective text, platforms text[] default '{}', content_plan jsonb default '{}', assets jsonb default '[]', status approval_status default 'draft', scheduled_start date, scheduled_end date, ai_generated boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table local_attractions (id uuid primary key default gen_random_uuid(), property_id uuid references properties(id) on delete cascade not null, name text not null, category text, description text, latitude numeric, longitude numeric, distance_km numeric, google_place_id text, rating numeric, price_level int, opening_hours jsonb default '{}', website text, phone text, affiliate_partner_id uuid, ai_relevance_score numeric, weather_suitability text, family_friendly boolean, created_at timestamptz default now());
create table opportunities (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade, title text not null, opportunity_type text not null, district text, province text default 'KwaZulu-Natal', description text, value_band text, start_date date, end_date date, eligibility jsonb default '{}', evidence_requirements jsonb default '[]', status text default 'active', created_at timestamptz default now());
create table business_profiles (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, property_id uuid references properties(id) on delete set null, business_name text not null, google_place_id text, website_url text, verification_status text default 'unverified', verified_signals jsonb default '{}', consistency_score numeric, created_at timestamptz default now(), updated_at timestamptz default now());
create table viability_analyses (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, opportunity_id uuid references opportunities(id) on delete cascade not null, business_profile_id uuid references business_profiles(id) on delete cascade not null, score numeric not null, confidence numeric not null, recommendation text not null, evidence jsonb not null default '[]', risks jsonb default '[]', actions jsonb default '[]', ai_model text, status approval_status default 'draft', created_at timestamptz default now());
create table participation_records (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, opportunity_id uuid references opportunities(id) on delete cascade not null, business_profile_id uuid references business_profiles(id) on delete cascade not null, status text default 'identified', owner_user_id uuid references auth.users(id), evidence jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now(), unique(opportunity_id,business_profile_id));
create table finance_records (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, property_id uuid references properties(id) on delete cascade, source_system text, external_id text, record_type text not null, amount numeric not null, currency text default 'ZAR', tax_amount numeric default 0, category text, booking_id uuid references bookings(id), status text default 'posted', transaction_date date default current_date, created_at timestamptz default now());
create table ai_recommendations (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, property_id uuid references properties(id) on delete cascade, recommendation_type text not null, title text not null, body text, confidence_score numeric, impact_estimate text, risk_level risk_level default 'medium', source_data jsonb default '{}', requires_approval boolean default true, status approval_status default 'draft', approved_by uuid references auth.users(id), executed_at timestamptz, created_at timestamptz default now());
create table ai_action_logs (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade, property_id uuid references properties(id) on delete cascade, user_id uuid references auth.users(id), model_provider text, model_name text, prompt_template_id text, input_summary text, output_summary text, action_type text, confidence_score numeric, risk_level risk_level default 'medium', approved boolean default false, approved_by uuid references auth.users(id), created_at timestamptz default now());
create table integration_accounts (id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id) on delete cascade not null, property_id uuid references properties(id) on delete cascade, provider text not null, status text default 'disconnected', auth_type text, encrypted_credentials_ref text, scopes text[] default '{}', last_sync_at timestamptz, last_error text, created_at timestamptz default now(), updated_at timestamptz default now());
create table integration_sync_logs (id uuid primary key default gen_random_uuid(), integration_account_id uuid references integration_accounts(id) on delete cascade not null, sync_type text, status text not null, started_at timestamptz default now(), completed_at timestamptz, records_processed int default 0, error_message text, retry_count int default 0);

create or replace function is_org_member(org uuid) returns boolean language sql security definer stable as $$ select exists(select 1 from organization_members where organization_id=org and user_id=auth.uid()); $$;
create or replace function can_access_property(prop uuid) returns boolean language sql security definer stable as $$ select exists(select 1 from properties p join organization_members om on om.organization_id=p.organization_id where p.id=prop and om.user_id=auth.uid()) or exists(select 1 from property_users pu where pu.property_id=prop and pu.user_id=auth.uid()); $$;

alter table organizations enable row level security; alter table organization_members enable row level security; alter table properties enable row level security; alter table property_users enable row level security; alter table units enable row level security; alter table guests enable row level security; alter table bookings enable row level security; alter table event_log enable row level security; alter table tasks enable row level security; alter table workflows enable row level security; alter table notifications enable row level security; alter table reviews enable row level security; alter table social_campaigns enable row level security; alter table local_attractions enable row level security; alter table opportunities enable row level security; alter table business_profiles enable row level security; alter table viability_analyses enable row level security; alter table participation_records enable row level security; alter table finance_records enable row level security; alter table ai_recommendations enable row level security; alter table ai_action_logs enable row level security; alter table integration_accounts enable row level security; alter table integration_sync_logs enable row level security;

create policy org_select on organizations for select using (is_org_member(id));
create policy org_update on organizations for update using (is_org_member(id));
create policy members_select on organization_members for select using (is_org_member(organization_id));
create policy properties_select on properties for select using (is_org_member(organization_id));
create policy properties_all on properties for all using (is_org_member(organization_id)) with check (is_org_member(organization_id));
create policy property_users_select on property_users for select using (can_access_property(property_id));
create policy units_all on units for all using (can_access_property(property_id)) with check (can_access_property(property_id));
create policy guests_all on guests for all using (is_org_member(organization_id)) with check (is_org_member(organization_id));
create policy bookings_all on bookings for all using (can_access_property(property_id)) with check (can_access_property(property_id));
create policy event_log_select on event_log for select using (organization_id is null or is_org_member(organization_id));
create policy tasks_all on tasks for all using (is_org_member(organization_id) and can_access_property(property_id)) with check (is_org_member(organization_id) and can_access_property(property_id));
create policy workflows_all on workflows for all using (is_org_member(organization_id)) with check (is_org_member(organization_id));
create policy notifications_select on notifications for select using (user_id=auth.uid() or is_org_member(organization_id));
create policy reviews_all on reviews for all using (can_access_property(property_id)) with check (can_access_property(property_id));
create policy campaigns_all on social_campaigns for all using (can_access_property(property_id)) with check (can_access_property(property_id));
create policy attractions_all on local_attractions for all using (can_access_property(property_id)) with check (can_access_property(property_id));
create policy opportunities_select on opportunities for select using (organization_id is null or is_org_member(organization_id));
create policy business_profiles_all on business_profiles for all using (is_org_member(organization_id)) with check (is_org_member(organization_id));
create policy viability_all on viability_analyses for all using (is_org_member(organization_id)) with check (is_org_member(organization_id));
create policy participation_all on participation_records for all using (is_org_member(organization_id)) with check (is_org_member(organization_id));
create policy finance_all on finance_records for all using (is_org_member(organization_id)) with check (is_org_member(organization_id));
create policy ai_recs_all on ai_recommendations for all using (is_org_member(organization_id)) with check (is_org_member(organization_id));
create policy ai_logs_select on ai_action_logs for select using (organization_id is null or is_org_member(organization_id));
create policy integrations_all on integration_accounts for all using (is_org_member(organization_id)) with check (is_org_member(organization_id));
create policy sync_logs_select on integration_sync_logs for select using (exists(select 1 from integration_accounts ia where ia.id=integration_account_id and is_org_member(ia.organization_id)));

create index idx_bookings_property_dates on bookings(property_id, check_in_date, check_out_date);
create index idx_tasks_property_status on tasks(property_id, status, due_at);
create index idx_events_org_type on event_log(organization_id, event_type, created_at desc);
create index idx_viability_score on viability_analyses(opportunity_id, score desc);
